absolute-paths-allowed-crates = ["std", "core", "alloc", "pyo3"]
absolute-paths-max-segments = 3
avoid-breaking-exported-api = false
check-inconsistent-struct-field-initializers = true
too-many-arguments-threshold = 10
