"""Type-check every docstring example — and every docs code fence — against the stubs.

``tools/gates/_check_docstring_examples.py`` proves the ``>>>`` examples execute and
print what they claim; this gate proves they also *type-check* — several
hundred real call sites become a free static-conformance corpus. An example
that only passes with a loosened stub (or that the stub rejects) fails here,
so docs, stubs, and runtime cannot drift apart pairwise.

A second lane does the same for the NON-executed ``python`` fences in
``docs/**/*.md`` (the ``exec="on"`` blocks already run under
``tools/gates/_check_examples.py``): gometry-only fences join the typed corpus with a
small prelude declaring the conventional free names docs fragments use;
fences demonstrating the competitor stacks (shapely/pyproj/h3/…) in the
migration guides are out of scope by import detection.

Mechanics: extract each docstring's example statements (outputs dropped) into
one synthetic module — one function per docstring, labeled with its qualname —
and run pyright + mypy over it.

Usage::

    .venv/bin/python tools/gates/_check_doctest_types.py

Exit 1 on any failure. The final line is ``TOTAL FAILURES: N``.
"""

from __future__ import annotations

import doctest
import re
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent.parent
_PYTHON = _ROOT / '.venv/bin/python'

_PREAMBLE = '''\
"""Synthetic module generated by tools/gates/_check_doctest_types.py — do not edit."""
# pyright: reportUnusedExpression=false
import gometry
import gometry as gm

'''

_DOCS = _ROOT / 'docs'
_FENCE = re.compile(r'```python([^\n]*)\n(.*?)```', re.DOTALL)
#: Fences importing (or assigning through) the competitor stacks are the
#: migration guides' "before" side — not gometry call sites.
_FOREIGN = re.compile(
    r'^\s*(?:import|from)\s+(?:shapely|pyproj|h3|s2sphere|rtree|geopandas|pandas)\b',
    re.MULTILINE,
)

_MD_PRELUDE = '''\
"""Synthetic module generated by tools/gates/_check_doctest_types.py — do not edit.

Docs prose fragments use a small conventional vocabulary of free names;
declaring them typed here keeps the fragments honest against the stubs.
"""
# pyright: reportUnusedExpression=false
import numpy as np
import numpy.typing as npt
import gometry
import gometry as gm

geom: gm.Geometry
arr: gm.GeometryArray
geoms: gm.GeometryArray
query: gm.Geometry
target: gm.CRS
obj: gm.Geometry
point: gm.Point
points: gm.GeometryArray[gm.Point]
millions: gm.GeometryArray[gm.Point]
lons: npt.NDArray[np.float64]
lats: npt.NDArray[np.float64]
elevations: npt.NDArray[np.float64]
timestamps: npt.NDArray[np.float64]
xy: npt.NDArray[np.float64]

'''


def _public_objects() -> list[tuple[str, object]]:
    import types

    import gometry

    objects: list[tuple[str, object]] = [('gometry', gometry)]
    for name in dir(gometry):
        if name.startswith('_'):
            continue
        obj = getattr(gometry, name)
        objects.append((f'gometry.{name}', obj))
        if isinstance(obj, type):
            for member in dir(obj):
                if member.startswith('_'):
                    continue
                attr = getattr(obj, member, None)
                if getattr(attr, '__doc__', None):
                    objects.append((f'gometry.{name}.{member}', attr))
        elif isinstance(obj, types.ModuleType):
            for member in getattr(obj, '__all__', None) or dir(obj):
                if member.startswith('_'):
                    continue
                attr = getattr(obj, member, None)
                if callable(attr) and getattr(attr, '__doc__', None):
                    objects.append((f'gometry.{name}.{member}', attr))
    return objects


def render_corpus() -> str:
    """The synthetic module: one function per example-carrying docstring."""
    parser = doctest.DocTestParser()
    chunks: list[str] = [_PREAMBLE]
    seen: set[int] = set()
    for index, (qualname, obj) in enumerate(_public_objects()):
        doc = getattr(obj, '__doc__', None)
        if not doc or '>>>' not in doc:
            continue
        marker = id(obj)
        if marker in seen:
            continue
        seen.add(marker)
        source = ''.join(example.source for example in parser.get_examples(doc))
        if not source.strip():
            continue
        fn_name = f'_example_{index}_{qualname.replace(".", "_")}'
        body = textwrap.indent(source, '    ')
        chunks.append(f'def {fn_name}() -> None:\n    # from {qualname}\n{body}\n')
    return '\n'.join(chunks)


def render_markdown_corpus() -> str:
    """One function per gometry-only non-exec docs fence, labeled path:line."""
    chunks: list[str] = [_MD_PRELUDE]
    index = 0
    for path in sorted(_DOCS.rglob('*.md')):
        text = path.read_text(encoding='utf-8')
        for match in _FENCE.finditer(text):
            info, body = match.group(1), match.group(2)
            if 'exec=' in info:
                continue  # executed (and thus checked) by _check_examples.py
            if _FOREIGN.search(body) or ('gm' not in body and 'gometry' not in body):
                continue
            lineno = text.count('\n', 0, match.start()) + 1
            rel = path.relative_to(_ROOT).as_posix()
            fn_name = f'_fence_{index}'
            index += 1
            chunks.append(
                f'def {fn_name}() -> None:\n'
                f'    # from {rel}:{lineno}\n'
                + textwrap.indent(body.rstrip() + '\n', '    ')
            )
    return '\n'.join(chunks)


def _check_file(label: str, target: Path, errors: list[str]) -> None:
    pyright = subprocess.run(
        ['pyright', str(target), '--pythonpath', str(_PYTHON)],
        cwd=_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if pyright.returncode != 0:
        errors.append(
            f'{label} pyright failed:\n' + (pyright.stdout + pyright.stderr).strip()
        )
    from mypy import api

    # Per-corpus cache directory — see the note in `_check_typing_runtime.py`.
    # Sharing mypy's default cache with the other typing gate keeps both
    # permanently cold; the two corpora also get separate directories so they
    # do not invalidate each other.  The corpus file itself lands in a fresh
    # temp path each run and so always misses, but its dependency graph
    # (gometry, numpy, the stub) is stable and is where the time goes.
    stdout, stderr, status = api.run([
        str(target),
        '--cache-dir',
        str(_ROOT / 'target' / 'mypy-cache' / f'doctest-{target.stem}'),
        '--no-error-summary',
        '--no-color-output',
    ])
    if status != 0:
        errors.append(f'{label} mypy failed:\n' + (stdout + stderr).strip())


def collect_errors() -> list[str]:
    corpora = {
        'doctest_corpus.py': render_corpus(),
        'docs_fence_corpus.py': render_markdown_corpus(),
    }
    errors: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        for name, corpus in corpora.items():
            failures_before = len(errors)
            target = Path(tmp) / name
            target.write_text(corpus, encoding='utf-8')
            _check_file(name, target, errors)
            if len(errors) > failures_before:
                keep = _ROOT / 'target' / name
                keep.parent.mkdir(exist_ok=True)
                keep.write_text(corpus, encoding='utf-8')
                errors.append(f'(corpus preserved at {keep})')
    return errors


def main() -> int:
    errors = collect_errors()
    for error in errors:
        print(error, file=sys.stderr)
        print(file=sys.stderr)
    print(f'TOTAL FAILURES: {len(errors)}')
    return 1 if errors else 0


if __name__ == '__main__':
    raise SystemExit(main())
