use super::*;

/// Serialize a CRS to WKT.
///
/// Parameters
/// ----------
/// crs : str or int
///     CRS as an EPSG code or authority/WKT string.
///
/// Returns
/// -------
/// str
pub(crate) fn crs_to_wkt(
    value: &Bound<'_, PyAny>,
    version: crs::WktVersion,
    pretty: bool,
    output_axis: crs::WktAxisRule,
    strict: bool,
    indentation_width: i128,
) -> PyResult<String> {
    let crs = crs_normalize(value)?;
    Ok(crs::to_wkt_with_options(
        &crs,
        version,
        &crs::CrsWktOptions {
            pretty,
            indentation_width: crs_validate_u8("WKT indentation_width", indentation_width, 1)?,
            output_axis: Some(output_axis),
            strict,
        },
    )?)
}

/// Serialize a CRS to PROJJSON text.
///
/// Parameters
/// ----------
/// crs : str or int
///     CRS as an EPSG code or authority/WKT string.
///
/// Returns
/// -------
/// str
pub(crate) fn crs_to_projjson(
    value: &Bound<'_, PyAny>,
    pretty: bool,
    indentation_width: i128,
) -> PyResult<String> {
    let crs = crs_normalize(value)?;
    Ok(crs::to_projjson_with_options(
        &crs,
        &crs::CrsProjJsonOptions {
            pretty,
            indentation_width: crs_validate_u8("PROJJSON indentation_width", indentation_width, 1)?,
        },
    )?)
}

/// Serialize a CRS to a PROJJSON mapping.
///
/// Parameters
/// ----------
/// crs : str or int
///     CRS as an EPSG code or authority/WKT string.
///
/// Returns
/// -------
/// dict
pub(crate) fn crs_to_projjson_dict(
    py: Python<'_>,
    value: &Bound<'_, PyAny>,
) -> PyResult<Py<PyDict>> {
    let crs = crs_normalize(value)?;
    let text = crs::to_projjson(&crs)?;
    let value: Value = serde_json::from_str(&text).map_err(|error| {
        CRSError::new_err(format!("invalid PROJJSON generated by PROJ: {error}"))
    })?;
    json_to_py(py, &value)?
        .bind(py)
        .cast::<PyDict>()
        .map_or_else(
            |_| {
                Err(CRSError::new_err(
                    "PROJJSON export did not produce an object",
                ))
            },
            |dict| Ok(dict.clone().unbind()),
        )
}

/// Serialize a CRS to a PROJ string.
///
/// Parameters
/// ----------
/// crs : str or int
///     CRS as an EPSG code or authority/WKT string.
///
/// Returns
/// -------
/// str
pub(crate) fn crs_to_proj(
    value: &Bound<'_, PyAny>,
    version: i64,
    pretty: bool,
    approximate_tmerc: bool,
    indentation_width: i64,
    max_line_length: i64,
) -> PyResult<String> {
    let crs = crs_normalize(value)?;
    let version = crs_proj_version(version)?;
    Ok(crs::to_proj(&crs, version, &crs::CrsProjOptions {
        pretty,
        indentation_width: crs_validate_u8(
            "PROJ indentation_width",
            i128::from(indentation_width),
            1,
        )?,
        max_line_length: crs_validate_usize("PROJ max_line_length", max_line_length)?,
        approximate_tmerc,
    })?)
}

pub(crate) fn crs_validate_u8(name: &str, value: i128, min: i128) -> PyResult<u8> {
    if (min..=i128::from(u8::MAX)).contains(&value) {
        return Ok(value as u8);
    }
    Err(CRSError::new_err(format!(
        "{name} must be between {min} and 255, got {value}"
    )))
}

pub(crate) fn crs_validate_usize(name: &str, value: i64) -> PyResult<usize> {
    if value > 0 {
        return usize::try_from(value)
            .map_err(|_| CRSError::new_err(format!("{name} must be at least 1")));
    }
    Err(CRSError::new_err(format!("{name} must be at least 1")))
}

pub(crate) fn crs_proj_version(value: i64) -> PyResult<crs::ProjStringVersion> {
    match value {
        4 => Ok(crs::ProjStringVersion::V4),
        5 => Ok(crs::ProjStringVersion::V5),
        _ => Err(CRSError::new_err("PROJ string version must be 5 or 4")),
    }
}

/// Descriptive information about a CRS.
///
/// Parameters
/// ----------
/// value : CRS-like
///     CRS as an EPSG code or authority/WKT string.
///
/// Returns
/// -------
/// dict
///     Descriptive CRS metadata (name, authority/code, datum, ellipsoid, axes).
///
/// Raises
/// ------
/// CRSError
///     If the value is not a recognized CRS.
///
/// Examples
/// --------
/// >>> import gometry as gm
/// >>> gm.crs_info(4326)['name']
/// 'WGS 84'
#[pyfunction]
pub(crate) fn crs_info(value: &Bound<'_, PyAny>) -> PyResult<crs::CrsInfo> {
    Ok((*crs::info(&crs_normalize(value)?)?).clone())
}
/// Identify candidate CRS matches for a definition.
///
/// Parameters
/// ----------
/// crs : str or int
///     CRS as an EPSG code or authority/WKT string.
///
/// Returns
/// -------
/// list
pub(crate) fn crs_identify(
    value: &Bound<'_, PyAny>,
    authority: Option<&str>,
) -> PyResult<Vec<crs::IdentifyCandidate>> {
    Ok(crs::identify(&crs_normalize(value)?, authority)?)
}

/// Best authority:code identifier for a CRS.
///
/// Parameters
/// ----------
/// crs : str or int
///     CRS as an EPSG code or authority/WKT string.
///
/// Returns
/// -------
/// tuple
pub(crate) fn crs_to_authority(
    value: &Bound<'_, PyAny>,
    authority: Option<&str>,
    min_confidence: u8,
) -> PyResult<Option<(String, String)>> {
    let crs = crs_normalize(value)?;
    Ok(crs::to_authority(
        &crs,
        authority,
        crs_min_confidence(min_confidence)?,
    )?)
}

/// EPSG code for a CRS, if any.
///
/// Parameters
/// ----------
/// crs : str or int
///     CRS as an EPSG code or authority/WKT string.
///
/// Returns
/// -------
/// int or None
pub(crate) fn crs_to_epsg(value: &Bound<'_, PyAny>, min_confidence: u8) -> PyResult<Option<i32>> {
    let crs = crs_normalize(value)?;
    Ok(crs::to_epsg(&crs, crs_min_confidence(min_confidence)?)?)
}

pub(crate) fn crs_min_confidence(value: u8) -> PyResult<crs::Confidence> {
    Ok(crs::Confidence::try_new("min_confidence", value)?)
}

/// Whether two CRS denote the same system.
///
/// Parameters
/// ----------
/// left, right : str or int
///     The two CRS to compare.
///
/// Returns
/// -------
/// bool
pub(crate) fn crs_same(
    left: &Bound<'_, PyAny>,
    right: &Bound<'_, PyAny>,
    comparison: crs::CrsComparison,
) -> PyResult<bool> {
    Ok(crs::same(
        &crs_normalize(left)?,
        &crs_normalize(right)?,
        comparison,
    )?)
}

/// Detail record for a single unit of measure.
///
/// Parameters
/// ----------
/// authority, code : str
///     Unit authority and code (e.g. ``'EPSG'``, ``'9001'``).
///
/// Returns
/// -------
/// dict
///     The unit-of-measure record (name, category, conversion factor).
#[pyfunction(signature = (authority, code))]
///
/// Examples
/// --------
/// >>> import gometry as gm
/// >>> gm.crs_unit('EPSG', '9001')['name']
/// 'metre'
pub(crate) fn crs_unit(authority: &str, code: &str) -> PyResult<crs::UnitInfo> {
    Ok(crs::unit_info(authority, code)?)
}

/// List the units of measure an authority defines.
///
/// Parameters
/// ----------
/// authority : str
///     Unit authority (e.g. ``'EPSG'``).
/// category : str, optional
///     Restrict to one unit category (e.g. ``'linear'``, ``'angular'``).
/// allow_deprecated : bool, default False
///     Whether deprecated units are included.
///
/// Returns
/// -------
/// list
///     One record per matching unit of measure.
#[pyfunction(signature = (authority, *, category = None, allow_deprecated = false))]
///
/// Examples
/// --------
/// >>> import gometry as gm
/// >>> gm.crs_units('EPSG')[0]['name']
/// '(bin)'
pub(crate) fn crs_units(
    authority: &str,
    category: Option<&str>,
    allow_deprecated: bool,
) -> PyResult<Vec<crs::UnitInfo>> {
    Ok(crs::units(authority, category, allow_deprecated)?)
}

/// List PROJ operations available.
///
/// Returns
/// -------
/// list
///     One entry per available PROJ operation.
#[pyfunction]
///
/// Examples
/// --------
/// >>> import gometry as gm
/// >>> gm.crs_proj_operations()[0]['id']
/// 'adams_hemi'
pub(crate) fn crs_proj_operations() -> Vec<crs::ProjOperationCatalogInfo> {
    crs::proj_operations()
}

/// List ellipsoids in the CRS database.
///
/// Returns
/// -------
/// list
///     One entry per ellipsoid in the CRS database.
#[pyfunction]
///
/// Examples
/// --------
/// >>> import gometry as gm
/// >>> gm.crs_ellipsoids()[0]['id']
/// 'MERIT'
pub(crate) fn crs_ellipsoids() -> Vec<crs::EllipsoidCatalogInfo> {
    crs::ellipsoids()
}

/// List prime meridians in the CRS database.
///
/// Returns
/// -------
/// list
///     One entry per prime meridian in the CRS database.
#[pyfunction]
///
/// Examples
/// --------
/// >>> import gometry as gm
/// >>> gm.crs_prime_meridians()[0]['id']
/// 'greenwich'
pub(crate) fn crs_prime_meridians() -> Vec<crs::PrimeMeridianCatalogInfo> {
    crs::prime_meridians()
}
